### ISSUE TITLE
Create "show backup phrase" page

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/ponferrada#10]
- [x] Create storybook with this screen (#81)
- [x] Add logic to show backup phrase of the current user (#81)
- [x] Add pdf generation and download (#82)

**Comment by albertandrejev** [comment]
Is there any layout or text for PDF document?

**Comment by kmw101** [comment]
Nothing fixed, I suggest you base it on the work done in the Demo Wallet?

**Comment by albertandrejev** [comment]
Hmm.. but there is no pdf download ability.

**Comment by kmw101** [comment]
The intention was to have a table with 2 columns:

| Order | Word |
|------|------|
| One | The |
| Two | quick |
| Three | Brown |
| Four | Fox |
| Five | Jumped |
| Six | Over |
| Seven | The |
| Eight | lazy |
| nine | dog |

etc

**Comment by albertandrejev** [comment]
ok, thank you

**Comment by albertandrejev** [comment]
Where to get pdf icon to use on this page?

**Comment by kmw101** [comment]
Can you ask Andrei?
