### ISSUE TITLE
Share identity view [UI]

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/ponferrada#16]
As a user shown a share identity request on the account status page.

I am shown the information about which site is requesting (through the signaling server) and for which token.

There are two buttons:
Accept
Reject

UX Guide: https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674193

- [x] Create storybook and view of the screen (PR #129)
- [x] Create storybook and view of the Reject screen (PR #138)
- [x] Add route and implement DOM tests (PR #150)

**Comment by kmw101** [comment]
Please ignore the confirmation page after accepting. It is not needed.

**Comment by prince272** [comment]
I've rewritten the Asp Core Identity for Mvc. Feel free to take a look at https://github.com/prince272/AspCoreIdentityMvc

Simply change the url for the area 'Identity' to 'IdentityMvc' and you'll be automatically directed to the Mvc version for Identity.

**Comment by kmw101** [comment]
Issue done
