### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#20]
As a user I am asked to enter and my password. 

The continue button remains inactive until an email address (checked with a regular expression for a @ and a "." in the address).

If I enter an incorrect email or password I am shown the error toaster with a message "Sorry you have entered either an incorrect email address or password".

A correct email and password takes me to the account status page.

I have options to click on Restore Account (go to restore page https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/341373581)
 and more options (Welcome page).

UX Guide: https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674175

- [x] Create storybook with component view implementation (PR #71)
- [x] Toast component implementation (PR #77)
- [x] Add toast to Login view (PR #83)

**Comment by albertandrejev** [comment]
But according to https://github.com/iov-one/ponferrada/issues/6 there is no need to check for email. Please correct me if I am wrong.

**Comment by kmw101** [comment]
This is an old reference, email has been replaced by unique identifier that the user set up in the registration process.

**Comment by albertandrejev** [comment]
- [ ] Create storybook with component view implementation
- [ ] Toast component implementation
- [ ] Logic to process login sequence

**Comment by kmw101** [comment]
As as user if I enter the wrong password I am shown the error message along with my security hint.

**Comment by webmaster128** [comment]
Closing since it is in the Done column
