### ISSUE TITLE
Balance page : Migrate balance page from wallet-demo

### ISSUE THREAD

**Issue by albertandrejev** [iov-one/ponferrada#276]
Migrate balance page from wallet-demo project and adapt page layout and redux configuration to ponferrado monorepo requirements.

- [x] Migrate PageMenu layout component (#366)
- [x] Migrate layout (#371)
- [x] Adapt layout to the ponferrado requirements (#371)
- [x] Create view storybook (#371)
- [ ] Add DOM and E2E tests (#382)
- [ ] Connect with redux (#381)
