### ISSUE TITLE
Core : Migrate Header component

### ISSUE THREAD

**Issue by albertandrejev** [iov-one/ponferrada#285]
Migrate `Header` component from `wallet-demo`

- [x] Migrate BadgeIcon (PR #298)
- [x] Migrate notifications reducer (PR #299)
- [x]  Migrate menu templates (PR #300)
- [x]  Migrate all variants based on txs statuses
- [x]  Upgrade storybook to show it.
