### ISSUE TITLE
Wallet - add registration functionality

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#895]
Changes:

- [x] "Your starnames" should be renamed to "Your iovnames"
- [x] In case of new starname registration, user can add blockchain addresses that he wants to connect to that starname. See design.
- [x] In case of new starname registration, user can also add or remove these addresses and then register the starname by clicking on "Register for 5 IOV".
- [x] "Back" button should be renamed to "Cancel"

Stages:
- [x] Component and titles renaming (PR #920)
- [x] Stacked form fields components (PR #924)
- [x] iovname registration (PR #925)
- [x] iovname update (PR #940)
- [x] DOM and E2E tests (PR #954)

<img width="1440" alt="Neuma Wallet - Your Starnames" src="https://user-images.githubusercontent.com/7419692/69974195-0b8d3c00-1525-11ea-9abe-b48f2bd1e500.png">

<img width="1440" alt="Neuma Wallet - Register Starname" src="https://user-images.githubusercontent.com/7419692/69974199-0d56ff80-1525-11ea-913d-3615d5cb56d3.png">
